debugged subset0

diff --git a/tigger-commit b/tigger-commit
--- a/tigger-commit
+++ b/tigger-commit
@@ -14,6 +14,12 @@
 #
 #######
 
+if [ ! -d ".tigger" ]
+then
+    echo "$0: error: tigger repository directory .tigger not found" 1>&2
+    exit 1
+fi 
+
 
 currBranch="$(cat .tigger/HEAD)"
 currBranchFolder=.tigger/branches/$currBranch
@@ -46,21 +52,20 @@ commitSubset0 () {
     
     # check if what's in index is the same as repo 
     isDiff=0
-    for f in $index/*
+    for f in "$index"/*
     do
-        temp=$(echo $f | tr '/' '\n' | tail -n 1)
+        temp=$(echo "$f" | tr '/' '\n' | tail -n 1)
         repoF=$repo/$temp
         if [ -f "$repoF" ]
         then
             # compare 
-            checkDiff=$(diff $f $repoF)
-            if ! diff $f $repoF >/dev/null 
+            if ! diff "$f" "$repoF" >/dev/null 
             then
                 # check if $f is a directory 
                 if [ ! -d "$f" ]
                 then
                     isDiff=1
-                    cp $f $repo 2>/dev/null
+                    cp "$f" "$repo" 2>/dev/null
                 fi
             fi
         else
@@ -68,7 +73,7 @@ commitSubset0 () {
             if [ ! -d "$f" ]
             then
                 isDiff=1
-                cp $f $repo 2>/dev/null
+                cp "$f" "$repo" 2>/dev/null
             fi
         fi
     done
@@ -91,11 +96,11 @@ commitSubset0 () {
     # if [ ! -s "$currBranchFolder/log" && -z  ]
     then 
         count=$(tail -1 "$currBranchFolder/log" | cut -d' ' -f 1)
-        count=$(($count+1))
+        count=$((count+1))
         commitFolder=".commit$count"
     fi
-    mkdir $index/$commitFolder
-    cp -f $index/* $index/$commitFolder 2>/dev/null
+    mkdir "$index"/"$commitFolder"
+    cp -f "$index"/* "$index"/"$commitFolder" 2>/dev/null
 
     # 3. record this commit with commit index and commit message to log
     # log format: 0 commit message
@@ -114,7 +119,7 @@ commitSubset1 () {
 
 # check arguments
 msgOnly=$(echo "$@" | grep -E '^-m .+$')
-if [ ! -z "$msgOnly" ]
+if [ -n "$msgOnly" ]
 then 
     commitSubset0 "$2"
 elif [ "$#" -eq 2 ]
diff --git a/tigger-show b/tigger-show
--- a/tigger-show
+++ b/tigger-show
@@ -4,13 +4,19 @@
 #   as of the specified commit. 
 # If commit is omitted, the contents of the file in the index should be printed.
 
+if [ ! -d ".tigger" ]
+then
+    echo "$0: error: tigger repository directory .tigger not found" 1>&2
+    exit 1
+fi 
+
 currBranch="$(cat .tigger/HEAD)"
-currBranchFolder=.tigger/branches/$currBranch
 index=.tigger/branches/$currBranch/index
 log=.tigger/branches/$currBranch/log
 
 
 # Errors:
+
 
 # 1. "usage: tigger-show <commit>:<filename>" >> multiple arguments | no arguments
 case $# in
@@ -25,8 +31,8 @@ case $# in
         exit 1
     fi
 
-    commit=$(echo $1 | cut -d ':' -f1)
-    fname=$(echo $1 | cut -d ':' -f2)
+    commit=$(echo "$1" | cut -d ':' -f1)
+    fname=$(echo "$1" | cut -d ':' -f2)
     ;;
 *)
     echo "usage: tigger-show <commit>:<filename>" 1>&2
@@ -45,7 +51,8 @@ esac
 # tigger-show: error: 'wp' not found in commit 0
 # tigger-show: error: 'wp' not found in index
 checkFile() {
-    if [ $(find $2 -name $1 | wc -l) -lt 1 ]
+    temp=$(find "$2" -name "$1" 2>/dev/null | wc -l)
+    if [ "$temp" -lt 1 ]
     then
         echo "$0: error: '$1' not found in $3"
         exit 1
@@ -56,25 +63,26 @@ checkFile() {
 # $2 - fname
 commit() {
     checkFile "$2" "$index/.commit$commit/$2" "commit $1"
-    cat $index/.commit$1/$2
+    cat < "$index"/.commit"$1"/"$2"
 }
 
 # 3. "tigger-show: error: invalid filename ''"
 # tigger-show: error: invalid object wowo
 index() {
     checkFile "$1" "$index/$2" "index"
-    cat $index/"$1"
+    cat < "$index"/"$1"
 }
 
-if [ -z $commit ]
+if [ -z "$commit" ]
 then
     # for arguments omitted commit, pass into index
     index "$fname"
 else
     # check if commit can be found
-    if ! cat $log | cut -d' ' -f1 | grep -E "^$commit$" > /dev/null
+    if ! cat < "$log" | cut -d' ' -f1 | grep -E "^$commit$" > /dev/null
     then
         echo "$0: error: unknown commit '$commit'"
+        exit 1
     fi
     commit "$commit" "$fname"
 fi
