debug rm

diff --git a/tigger-add b/tigger-add
--- a/tigger-add
+++ b/tigger-add
@@ -17,13 +17,20 @@ then
 fi
 
 branch="$(cat .tigger/HEAD)"
+repo=.tigger/branches/"$branch"/index
 for f in "$@"
 do 
     if [ ! -f "$f" ]
     then
-        echo "$0: error: can not open '$f'" 1>&2
-        exit 1
+        if [ -f "$index"/"$f" ]
+        then
+            rm "$index"/"$f"
+        else
+            echo "$0: error: can not open '$f'" 1>&2
+            exit 1
+        fi
+    else
+        cp "$f" .tigger/branches/"$branch"/index
     fi
-    cp "$f" .tigger/branches/"$branch"/index
 done
 
diff --git a/tigger-rm b/tigger-rm
--- a/tigger-rm
+++ b/tigger-rm
@@ -179,9 +179,19 @@ do
             warning "$f"
             removeIndex "$f"
             removeWorkingDir "$f"
+        elif [ "$isForce" -eq 1 ] && [ "$isCached" -eq 1 ]
+        then    
+            removeIndex "$f"
         elif [ "$isCached" -eq 1 ] 
         then
-            if ! diff "$index"/"$f" "$repo"/"$f" >/dev/null && ! diff "$f" "$index"/"$f" >/dev/null
+            if [ ! -f "$repo"/"$f" ]
+            then
+                if ! diff "$f" "$index"/"$f" >/dev/null
+                then
+                    echo "tigger-rm: error: '$f' in index is different to both the working file and the repository" 1>&2
+                    exit 1
+                fi
+            elif ! diff "$index"/"$f" "$repo"/"$f" >/dev/null && ! diff "$f" "$index"/"$f" >/dev/null
             then
                 if [ "$isForce" -ne 1 ]
                 then
