implemented tigger-rm

diff --git a/tigger-rm b/tigger-rm
--- a/tigger-rm
+++ b/tigger-rm
@@ -35,6 +35,7 @@
 # * no error when 'a' not in current directory but in index
 
 
+
 currBranch="$(cat .tigger/HEAD)"
 currBranchFolder=.tigger/branches/$currBranch
 index=.tigger/branches/$currBranch/index
@@ -46,7 +47,7 @@ isForce=0
 # Check if there is a repository
 if [ ! -d ".tigger" ]
 then
-    echo "$0: error: tigger repository directory .tigger not found" 1>&2
+    echo "tigger-rm: error: tigger repository directory .tigger not found" 1>&2
     exit 1
 fi 
 
@@ -129,34 +130,70 @@ fi
 # If not, raise an error
 # TODO: check between repo and working directory as well 
 warning() {
+    # if file in index but not in repo
     if [ ! -f "$repo"/$1 ]
     then
+        if ! diff "$index"/$1 $1 >/dev/null
+        then
+            echo "tigger-rm: error: '$1' in index is different to both the working file and the repository" 1>&2
+            exit 1
+        fi
         echo "tigger-rm: error: '$1' has staged changes in the index" 1>&2
         exit 1
-    fi 
-    else if ! diff "index"/$1 "$repo"/$1 >/dev/null 
+    elif ! diff "$index"/$1 "$repo"/$1 >/dev/null && ! diff $1 "$index"/$1 >/dev/null
+    then
+        echo "tigger-rm: error: '$1' in index is different to both the working file and the repository" 1>&2
+        exit 1
+    elif ! diff "$index"/$1 "$repo"/$1 >/dev/null 
     then
         echo "tigger-rm: error: '$1' has staged changes in the index" 1>&2
         exit 1
+    elif ! diff $1 "$repo"/$1 >/dev/null
+    then
+        echo "tigger-rm: error: '$1' in the repository is different to the working file" 1>&2
+        exit 1
     fi
-    else
-        return 0
+
+    # return 0
 }
+
+removeIndex() {
+    rm "$index"/$1
+}
+
+removeWorkingDir() {
+    rm $1
+}
+
+# index same with repo
+# or index same with curr dir
+# curr dir same with repo don't matter
 
 for f in "$@"
 do 
     if ! echo "$f" | grep -E '^--.*' >/dev/null
     then
         ### do something 
-        if [ isForce != 1 && isCached != 1 ]
+        if [ "$isForce" -ne 1 ] && [ "$isCached" -ne 1 ]
         then
             warning "$f"
-        fi
-        else if [ isCached == 1 ]
+            removeIndex "$f"
+            removeWorkingDir "$f"
+        elif [ "$isCached" -eq 1 ] 
         then
-            removeIndex
+            if ! diff "$index"/"$f" "$repo"/"$f" >/dev/null && ! diff "$f" "$index"/"$f" >/dev/null
+            then
+                if [ "$isForce" -ne 1 ]
+                then
+                    echo "tigger-rm: error: '$f' in index is different to both the working file and the repository" 1>&2
+                    exit 1
+                fi
+            fi
+            removeIndex "$f"
+        elif [ "$isForce" -eq 1 ]
+        then
+            removeIndex "$f"
+            removeWorkingDir "$f"
         fi
-        else 
-
     fi
 done
diff --git a/tigger-show b/tigger-show
--- a/tigger-show
+++ b/tigger-show
@@ -6,7 +6,7 @@
 
 if [ ! -d ".tigger" ]
 then
-    echo "$0: error: tigger repository directory .tigger not found" 1>&2
+    echo "tigger-show: error: tigger repository directory .tigger not found" 1>&2
     exit 1
 fi 
 
@@ -27,7 +27,7 @@ case $# in
 1) 
     if ! echo "$1" | grep ':' >/dev/null
     then 
-        echo "$0: error: invalid object $1" 1>&2
+        echo "tigger-show: error: invalid object $1" 1>&2
         exit 1
     fi
 
@@ -43,33 +43,25 @@ esac
 # 2. "tigger-show: error: unknown commit '10'"
 #   a. check if commit is omitted
 
-# a function to check if a filename exist in a folder
-# $1: filename
-# $2: folder name
-# $3: type (index or commit --> with commit number)
-
-# tigger-show: error: 'wp' not found in commit 0
-# tigger-show: error: 'wp' not found in index
-checkFile() {
-    temp=$(find "$2" -name "$1" 2>/dev/null | wc -l)
-    if [ "$temp" -lt 1 ]
-    then
-        echo "$0: error: '$1' not found in $3"
-        exit 1
-    fi
-}
-
 # $1 - commit index
 # $2 - fname
 commit() {
-    checkFile "$2" "$index/.commit$commit/$2" "commit $1"
+    if [ ! -f "$index"/.commit$1/$2 ]
+    then
+        echo "tigger-show: error: '$2' not found in commit $1"
+        exit 1
+    fi
     cat < "$index"/.commit"$1"/"$2"
 }
 
 # 3. "tigger-show: error: invalid filename ''"
 # tigger-show: error: invalid object wowo
 index() {
-    checkFile "$1" "$index/$2" "index"
+    if [ ! -f "$index"/$1 ]
+    then
+        echo "tigger-show: error: '$1' not found in index"
+        exit 1
+    fi
     cat < "$index"/"$1"
 }
 
@@ -81,7 +73,7 @@ else
     # check if commit can be found
     if ! cat < "$log" | cut -d' ' -f1 | grep -E "^$commit$" > /dev/null
     then
-        echo "$0: error: unknown commit '$commit'"
+        echo "tigger-show: error: unknown commit '$commit'"
         exit 1
     fi
     commit "$commit" "$fname"
